version: '3'

services:
  backend:
    build: .
    ports:
      - 9000:9000
    depends_on:
      - mysql
    volumes: 
      - ./src:/usr/src/gastos/src
    restart: always

  mysql:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
