version: '3'

services:
  backend:
    build: .
    ports:
      - 9000:9000
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/gastos/src
    restart: always

  postgres:
    image: postgres
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
